# SAP Commerce Suite 2211
# See https://me.sap.com/softwarecenterviewer/73554900100900007112/INST to determine new download URLs
com.sap.softwaredownloads.commerceSuite.2211.37.downloadUrl=https://softwaredownloads.sap.com/file/0020000000264042025
com.sap.softwaredownloads.commerceSuite.2211.37.checksum=293aa808ba69b97e259f25c861c2a33a242b67becab05a4105d52a88de47b7f5

com.sap.softwaredownloads.commerceSuite.2211.38.downloadUrl=https://softwaredownloads.sap.com/file/0020000000378152025
com.sap.softwaredownloads.commerceSuite.2211.38.checksum=b3ddb935b964d36a25e016bde49549d92d52e1bb6ed42c8b4cbc2801b445632b

com.sap.softwaredownloads.commerceSuite.2211.39.downloadUrl=https://softwaredownloads.sap.com/file/0020000000471252025
com.sap.softwaredownloads.commerceSuite.2211.39.checksum=28b554c19ed0b44875cd257cb8260cae7967d550699b19e0cfaea714d7e5be5a

# SAP Commerce Suite 2211 JDK 21
# See https://me.sap.com/softwarecenterviewer/73554900100900009192/INST to determine new download URLs
com.sap.softwaredownloads.commerceSuite.2211-jdk21.4.downloadUrl=https://softwaredownloads.sap.com/file/0025000000117912025
com.sap.softwaredownloads.commerceSuite.2211-jdk21.4.checksum=9d936722562638acadceb59464dbe57356a58d4e3d97d54e957c9e45c674164b

# SAP Commerce Integrations 2211
# See https://me.sap.com/softwarecenterviewer/73554900100900007161/INST to determine new download URLs
com.sap.softwaredownloads.commerceIntegrations.2211.32.downloadUrl=https://softwaredownloads.sap.com/file/0020000000263852025
com.sap.softwaredownloads.commerceIntegrations.2211.32.checksum=14447c6c8783729687818c49b0ea655693a525bac3a689402f175b1d52c9a147

com.sap.softwaredownloads.commerceIntegrations.2211.33.downloadUrl=https://softwaredownloads.sap.com/file/0020000000378082025
com.sap.softwaredownloads.commerceIntegrations.2211.33.checksum=f6a7eecae2f310ba2707998b6e6ee023d2a96e364b6c5221e6ded2f1fb620a8f

com.sap.softwaredownloads.commerceIntegrations.2211.34.downloadUrl=https://softwaredownloads.sap.com/file/0020000000471172025
com.sap.softwaredownloads.commerceIntegrations.2211.34.checksum=86076d512c0515f286330fefc4b847f7b2f1b50bab41e98842bce075cf068730

# SAP Commerce Integrations 2211 JDK 21
# See https://me.sap.com/softwarecenterviewer/73554900100900009421/INST to determine new download URLs
com.sap.softwaredownloads.commerceIntegrations.2211-jdk21.1.downloadUrl=https://softwaredownloads.sap.com/file/0020000000988642025
com.sap.softwaredownloads.commerceIntegrations.2211-jdk21.1.checksum=ca0f21d39b7dea5366466df292f118523dfa9fe761cd332d87065f1f30faf9cf
